### ISSUE TITLE
Use `humantime` to parse config time values

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#175]
The aim of this task is to use above crate to parse all time related values, eg:
![image](https://github.com/iggy-rs/iggy/assets/5490304/348e258c-86e3-444f-a991-16020f339db9)

I might have skipped some of the entries in the config, so contributor should thoroughly check config for server and determine which values are time-related.

**Comment by berendsliedrecht** [comment]
This is already implemented, looking at the code within `IggyDuration`.
