### ISSUE TITLE
Merge `iggy-cli` and `iggy-cmd`

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#179]

**Comment by BartoszCiesla** [comment]
For now `iggy-cli` to be removed and `iggy-cmd` to be renamed to `cli`. But first https://github.com/iggy-rs/iggy/issues/293 is needed.

**Comment by hubcio** [comment]
+ remove `iggy-cli` from docker image

**Comment by BartoszCiesla** [comment]
This one needs #428 ready (in order to cover all examples from README)
