### ISSUE TITLE
Make number of personal access tokens configurable

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#181]

**Comment by vdnhi** [comment]
Hi @hubcio , could you give more description for this issue? As I understand, we are currently setting a hardcode of 100 for max personal access token, so this ticket is to make it configurable. Is it server-wide config and only users with `manage_servers` permission can set this value?

**Comment by hubcio** [comment]
just for history, im gonna paste SS from discord:
![image](https://github.com/iggy-rs/iggy/assets/5490304/f188ece3-c421-4ab6-b721-92f8c9528ffc)
