### ISSUE TITLE
Improve error logging in server

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#198]
The aim of this task is to review the whole `iggy-server` code and add print when something goes wrong.

Example:
```rust
#[async_trait]
impl SegmentStorage for FileSegmentStorage {
    async fn load_messages(
        &self,
        segment: &Segment,
        index_range: &IndexRange,
    ) -> Result<Vec<Arc<Message>>, Error> {
        let mut messages = Vec::with_capacity(
            1 + (index_range.end.relative_offset - index_range.start.relative_offset) as usize,
        );
        load_messages_by_range(segment, index_range, |message: Message| {
            messages.push(Arc::new(message));
            Ok(())
        })
        .await?;
        trace!("Loaded {} messages from disk.", messages.len());
        Ok(messages)
    }
```

If `load_messages_by_range` goes wrong, message in logs will be, lightly said, not informative enough:
`2023-10-18T11:05:48.787778Z ERROR iggy_server::streaming::streams::storage: Failed to load topic with ID: 1 for stream with ID: 3000009.`

There are two ways of solving this issue.
- use `anyhow` and `.with_context()`
- extend `ServerError` with proper string payload

Contributor should decide what should we use (maybe both in some cases? IMHO both are idiomatic)

**Comment by numinnex** [comment]
I take this issue.
