### ISSUE TITLE
`iggy-bench` improvements

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#230]
`2023-10-29T12:57:37.299356Z  INFO iggy_bench::benchmarks::send_and_poll_benchmark: Benchmark: send and poll messages, transport: tcp, total messages: 10000000, total size: 10000000000 bytes, 10 streams, 1000 messages per batch, 1000 batches, 1000 bytes per message, 10 producers, 10 consumers`

`2023-10-29T12:57:37.299362Z  INFO iggy_bench::benchmark_runner: Results: total throughput: 2188.89 MB/s, 2244713 messages/s, average latency: 8.78 ms, average client throughput: 109.44 MB/s, total duration: 8.91 s`

The aim of this task is change two things regarding above prints:
- in the first print, change amount units to human friendly output, eg. `50000000` should be `50 M` and bytes size units should be treated similarly, eg. `50000000000 bytes` should be `50 GB`
- in the second print, only for `send-and-poll` benchmark, split it into two separate prints, one for consumer clients and other for producer clients

You can run benchmark with command `cargo run --bin iggy-bench -- -v -c send-and-poll tcp`

**Comment by Molter23** [comment]
I will take care of it.

**Comment by Molter23** [comment]
Something like it is okay? @hubcio 
```
2023-11-07T19:51:20.565587Z  INFO iggy_bench::benchmarks::send_and_poll_benchmark: Benchmark: send and poll messages, transport: tcp, total messages: 10.00 M, total size: 9.3 GiB bytes, 10 streams, 1000 messages per batch, 1000 batches, 1000 bytes per message, 10 producers, 10 consumers
2023-11-07T19:51:20.565638Z  INFO iggy_bench::benchmark_runner: Producer results: total throughput: 633.95 MB/s, 664744 messages/s, average latency: 15.04 ms, average throughput: 31.70 MB/s, total duration: 15.04 s
Consumer results: total throughput: 649.69 MB/s, 651911 messages/s, average latency: 14.69 ms, average  throughput: 32.48 MB/s, total duration: 15.34 s
Results: total throughput: 641.90 MB/s, 658265 messages/s, average latency: 29.73 ms, average  throughput: 32.09 MB/s, total duration: 30.38 s
```

**Comment by hubcio** [comment]
> Something like it is okay? @hubcio
> 
> ```
> 2023-11-07T19:51:20.565587Z  INFO iggy_bench::benchmarks::send_and_poll_benchmark: Benchmark: send and poll messages, transport: tcp, total messages: 10.00 M, total size: 9.3 GiB bytes, 10 streams, 1000 messages per batch, 1000 batches, 1000 bytes per message, 10 producers, 10 consumers
> 2023-11-07T19:51:20.565638Z  INFO iggy_bench::benchmark_runner: Producer results: total throughput: 633.95 MB/s, 664744 messages/s, average latency: 15.04 ms, average throughput: 31.70 MB/s, total duration: 15.04 s
> Consumer results: total throughput: 649.69 MB/s, 651911 messages/s, average latency: 14.69 ms, average  throughput: 32.48 MB/s, total duration: 15.34 s
> Results: total throughput: 641.90 MB/s, 658265 messages/s, average latency: 29.73 ms, average  throughput: 32.09 MB/s, total duration: 30.38 s
> ```

yes, but split it to 3 different prints
