### ISSUE TITLE
Custom Error type

### ISSUE THREAD

**Issue by spetz** [iggy-rs/iggy#37]
Refactor the existing `Error` into more concise (and easier to use) component with a helper methods for converting the values to/from string, int etc.

**Comment by daniel-pape** [comment]
Hello @spetz: I got interested in this and ended up with the attached proposal. Maybe this could serve as a first step in the direction you had in mind? I guess you maybe thought about adding macro functionality to add the helper methods(?) to arrive at a more compact errors.rs file? While thinking about a way how one might approach this I thought the proposed approach might be helpful to keep the actual underlying data more manageable. Would be interested what you think. As said: just an idea but I thought it would be easier to discuss if one could take a look at it. If you were actually thinking about something different, please let me know.

**Comment by hubcio** [comment]
Closing upon merging #64 and #90.

**Comment by hubcio** [comment]
Closing upon merging https://github.com/iggy-rs/iggy/pull/64 and https://github.com/iggy-rs/iggy/pull/90.
