### ISSUE TITLE
Discord link has expired

### ISSUE THREAD

**Issue by seroze** [iggy-rs/iggy#4]
Hi @spetz , the discord link is not working. Can you update it with a working link.

**Comment by spetz** [comment]
Hey @seroze, I've just checked the link, and the redirection seems to be working just fine - it does point to the same URL https://discord.gg/BxPeaVcuTK - what's the issue on your side?

**Comment by seroze** [comment]
![image](https://github.com/iggy-rs/iggy/assets/87276744/d2f6011c-54ae-4974-abf2-ab1e6ef58fa8)

**Comment by spetz** [comment]
Hmmm weird, as some new members have joined recently. Nevertheless, I've just configured a new link, so please try to join again https://iggy.rs/discord :)

**Comment by seroze** [comment]
> Hmmm weird, as some new members have joined recently. Nevertheless, I've just configured a new link, so please try to join again https://iggy.rs/discord :)

I think the issue is with my local app installation on laptop, I tried to join the link on my mobile and it seems to work fine.

**Comment by spetz** [comment]
Great to hear!
