### ISSUE TITLE
Add consumer offset get and set commands to cli

### ISSUE THREAD

**Issue by BartoszCiesla** [iggy-rs/iggy#545]

**Comment by ashiskumarnaik** [comment]
Hi @BartoszCiesla I Wanted to work on this issue. If there are specific considerations or additional information I should be aware of, please let me know.

**Comment by BartoszCiesla** [comment]
Thanks @ashiskumarnaik, go ahead. There's one important point to consider - since cli does not have session (same as http), there's no possibility to use `ConsumerGroup` as `Consumer` type - so only "regular" Consumer can be used (same as in `message` `poll` cli commands, see implementation of that cli command).

**Comment by BartoszCiesla** [comment]
@ashiskumarnaik do you need any assistance with this issue? When do you plan to post PR?
