### ISSUE TITLE
Deleting streams/topics does not reduce serve auto-increment counter.

### ISSUE THREAD

**Issue by gibbz00** [iggy-rs/iggy#597]
Adding ten topics and then deleting them all will have the next topic ID still start at 11. Maybe the next value calculation should be redone upon such deletions 😊

**Comment by spetz** [comment]
Good point, however it's not as simple as just decrementing the value, as you can remove any topic, so it's more about filling up the "holes" in missing values - will work on it :)

**Comment by gibbz00** [comment]
I think just setting current max value +1 is more than enough, and a lot simpler.

**Comment by spetz** [comment]
I've just pushed a simple fix.
