### ISSUE TITLE
Fix nested env var config overriding

### ISSUE THREAD

**Issue by spetz** [iggy-rs/iggy#61]
The current implementation of `ConfigProvider` uses the following code, to allow the overriding of server configuration via environment variables:

```rust
let config: Result<ServerConfig, figment::Error> = config_builder
    .merge(Env::prefixed("IGGY_").split("_"))
    .extract();
```

For example, the following setting:

```toml
[system.database]
path = "database"
```

Can be easily overwritten with:

```
export IGGY_SYSTEM_DATABASE_PATH=mydb
```

However, this will not work with the underscored field names, such as:

```toml
[quic.certificate]
self_signed = true
```

Will not be updated with:

```
export IGGY_QUIC_SELF_SIGNED=false
```

More information about this issue can be found [here](https://github.com/SergioBenitez/Figment/issues/12) and in the mentioned [nesting docs](https://docs.rs/figment/0.10.3/figment/providers/struct.Env.html#key-paths-nesting).

**Comment by hubcio** [comment]
I will take care of this.
