### ISSUE TITLE
Add support for message headers to send and poll commands

### ISSUE THREAD

**Issue by BartoszCiesla** [iggy-rs/iggy#646]
Message headers are defined in `sdk/src/models/header.rs`. Each header is defined Key,Value pair where key is always a string while value can be string, bool or numerical. Message can contain multiple headers.

**Comment by BartoszCiesla** [comment]
For `message poll` add option which will allow to enable / disable showing headers, each header shall be printed in separate column (?). Add option for selecting output as in other commands
```
  -l, --list-mode <LIST_MODE>
          List mode (table or list)
          
          [default: table]
          [possible values: table, list]
```

**Comment by SailnMobula** [comment]
Hey. I will try my very best on this. Like discussed on Discord we go for this approach. 
1. For each key-value pair in a message header, there should be a new column. The Header should show also the value type.
2. We provide an option flag to print the message header for `message poll`. I would suggest
```
    -s, --show-headers    Include the message headers in the output
```
3. We provide a header option for the `message send` command which provides a list of key-value pairs like
```
    --header key1:type:value,key2:type:value
```
@BartoszCiesla feel free to correct me, if i got somethink wrong.

**Comment by BartoszCiesla** [comment]
LGTM @SailnMobula, I'll assign this ticket to you.

**Comment by BartoszCiesla** [comment]
@SailnMobula do you plan any PR for this issue?

**Comment by BartoszCiesla** [comment]
No problem @SailnMobula, take your time.

**Comment by BartoszCiesla** [comment]
@SailnMobula thanks for the contribution. I'll close the ticket.
