### ISSUE TITLE
Remove printing full payload of commands in `iggy-server`

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#657]
The aim of this issue is to reduce iggy-server excessive printing of full command payload. This loads to gigabytes sent to stdout.

Run iggy server via
`RUST_LOG=trace cargo run --bin iggy-server`
check which commands print payload, and replace it with printing first 20 bytes and last 20 bytes of payload.

**Comment by pradovic** [comment]
Hi 👋  I tried Iggy and love it. I have some spare time so I would like to contribute. May I take this one for start?

**Comment by hubcio** [comment]
@pradovic ofcourse! join our discord to ask if you have any problem when implementing it.

I assigned this issue for you.

**Comment by pradovic** [comment]
Thanks, I joined the discord as well. May I ask for a short clarification. By payload, do did you mean the actual message payload (as in `SendMessages`), or basically arbitrary `Command` that contains a payload?
For example, if the command is `PollMessages(PollMessages)`, would you consider the display value of `PollMessages` a payload to be shown with first 20 and last 20 characters?
Also, does the format like `first_20...last_20` sounds ok?

**Comment by hubcio** [comment]
@pradovic thanks for joining discord, I hope everything is clear now :D
