### ISSUE TITLE
Upon reaching the maximum offset of a message, how is iggy handled?

### ISSUE THREAD

**Issue by iamazy** [iggy-rs/iggy#866]
If the message offset reaches the maximum value of `u64`, how would Iggy handle it?

**Comment by hubcio** [comment]
@iamazy 
Well, we didn't account for this many messages. Assuming you have 1 million messages per second, it would take 60 000 years to fill this counter. There is no condition, nor any check regarding reaching max offset. So, currently it's undefined behavior.

**Comment by iamazy** [comment]
> @iamazy Well, we didn't account for this many messages. Assuming you have 1 million messages per second, it would take 60 000 years to fill this counter. There is no condition, nor any check regarding reaching max offset. So, currently it's undefined behavior.

Thanks
